site_name: Dev beginner tutorial
site_description: Dev beginner tutorial
site_author: Sotetsu KOYAMADA
site_url: http://sotets.uk/dev-beginner-tutorial
repo_name: sotetsuk/dev-beginner-tutorial
repo_url: https://github.com/sotetsuk/dev-beginner-tutorial
copyright: Copyright &copy 2020 Sotetsu KOYAMADA
nav:
    - Home: index.md
    - Unix command: unix_command.md
    - Python: python.md
    - Git: git.md
    - GitHub: github.md
    - Python practice: python_practice.md
    - C++: cpp.md
    - Docker: docker.md
theme:
  name: material
  language: ja
  palette:
    scheme: slate
    primary: teal
    accent: orange
  font:
    text: Noto Sans
    code: Inconsolata
markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true